server: 
  port: 8080
  servlet:
    context-path: /${spring.application.name}
spring: 
  application:
    name: web_main
  jmx:
    enabled: false
#    default-domain: ${spring.application.name}