##############################################################################
config.test.val : weiweitest

spring: 
    #jta相关参数配置
#    jta:
#      log-dir: classpath:tx-logs
#      #transaction-manager-id: txManager
#    resources:
#      static-locations:
  datasource:
    type: com.atomikos.jdbc.AtomikosDataSourceBean
    source1:
      name: orcl221
      url: jdbc:oracle:thin:@172.16.161.211:1521:orcl
      username: tscp_dev
      password: tscp_dev
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select * from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      useGlobalDataSourceStat: true
    source2:
      name: orcl161
      url: jdbc:oracle:thin:@172.16.161.211:1521:orcl
      username: tms3_test
      password: tms3_test
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20   
      useGlobalDataSourceStat: true
    #redis配置
  redis:
    host: 172.16.161.162
    port: 6379
    password: senyint123
    timeout: 30000
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 8
      min-idle: 0
mybatis:
  mapper-locations: classpath*:com/senyint/entity/**/mapper/*.xml
  type-aliases-package: com.senyint.entity
mapper:
  mappers:  com.senyint.persistent.mybatis.CommonMapper
  not-empty: false
  identity: ORACLE
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
  autoRuntimeDialect: true  

