
# ################################# 应用服务器配置 ##################################
server:
  port: 8881
  
spring:
  application:
    name: plugin_eureka
  profiles:
    #启用对应的配置名称
    active: dev
  jmx:
    enabled: false
# ################################# 注册中心配置 ##################################
eureka:
  client:
    #不作为一个客户端注册到注册中心 
    registerWithEureka: false
    #禁止检索服务
    fetchRegistry: false
  dashboard:
    path: eurekaui
---
##开发配置名称
spring:
  profiles: dev
#eureka:
#  server:
#    enable-self-preservation: false #Eureka自我保护机制以及心跳周期长会遇到 Eureka不剔除已关停的节点的问题，默认打开状态。建议生产环境打开此配置
#    eviction-interval-timer-in-ms: 4000 #清理间隔（单位毫秒，默认是60*1000）
---
##生产配置名称
spring:
  profiles: prod
  ##开启安全机制
  security:
    user:
      name: admin
      password: peiwei



